language: go
sudo: false

script:
  - GOPATH=$TRAVIS_BUILD_DIR
  - go test example1 example2 -json > testdata.json

after_script:
  - python <(curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py)